name: deploy page

on:
  # 每当 push 到 master 分支时触发部署
  push:
    branches: [master]
  # 手动触发部署
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 拉取最新代码
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          # 选择要使用的 node 版本
          node-version: '14'

      # 安装依赖
      - name: Install pnpm
        run: npm i -g pnpm

      # 安装依赖
      - name: Install dependencies
        run: pnpm i

      # 运行文档构建脚本
      - name: Build VitePress site
        run: pnpm run build

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 gh-pages 分支
          target_branch: pages
          # 部署目录为 VitePress 的默认输出目录
          build_dir: .vitepress/dist
        env:
          # 此处需要配置自己GitHub仓库的secrets，添加TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: Sync to Gitee
      #   uses: wearerequired/git-mirror-action@master
      #   env:
      #     # 在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
      #     SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      #   with:
      #     # GitHub 源仓库地址
      #     source-repo: git@github.com:nkxrb/nkxrb.github.io.git
      #     # Gitee 目标仓库地址
      #     destination-repo: git@gitee.com:nkxrb/nkxrb.github.io.git